/**
 * gyg_mock.js — GetYourGuide mock adapter for activities.
 *
 * Simulates a rich activity marketplace for
 * 5 demo cities: Istanbul, Bangkok, Rome, Dubai, Barcelona.
 *
 * Implements the same interface as adapters/wikivoyage.js so the service
 * layer can switch providers via the ACTIVITY_PROVIDER env var without
 * touching the route or the frontend.
 *
 * Returned schema is identical to wikivoyage.js ({ type, sections, ... }),
 * with additional enrichment fields (rating, reviews, thumbnail, bookingLink,
 * priceAmount, currency) that are currently ignored by the frontend but
 * available for future enhancements.
 */

// ── Data: 5 demo cities ─────────────────────────────────────────
const CITIES = {
    istanbul: {
        type: "listings",
        sections: [
            {
                section: "See", category: "Sights",
                listings: [
                    {
                        name: "Hagia Sophia Grand Mosque",
                        description: "Explore the magnificent 6th-century Byzantine cathedral, later an Ottoman mosque, now one of the most iconic landmarks in the world.",
                        address: "Sultan Ahmet, 34122 Fatih/Istanbul",
                        url: "https://muze.gov.tr/hagiasophia",
                        hours: "09:00 – 19:00",
                        price: "Free",
                        phone: "+90 212 522 1750",
                        lat: 41.0086, lon: 28.9802,
                        rating: 4.8, reviews: 125000,
                        thumbnail: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/hagia-sophia-tour",
                        priceAmount: 0, currency: "EUR",
                    },
                    {
                        name: "Topkapi Palace Museum",
                        description: "Former palace of Ottoman sultans with its treasury, harem, and archaeological collections spanning five centuries.",
                        address: "Cankurtaran, 34122 Fatih/Istanbul",
                        url: "https://muze.gov.tr/topkapi",
                        hours: "09:00 – 18:00 (closed Tuesdays)",
                        price: "€20",
                        phone: "+90 212 512 0480",
                        lat: 41.0115, lon: 28.9833,
                        rating: 4.7, reviews: 89000,
                        thumbnail: "https://images.unsplash.com/photo-1570645778867-e8a5e9a5d8b0?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/topkapi-palace",
                        priceAmount: 20.00, currency: "EUR",
                    },
                    {
                        name: "Blue Mosque",
                        description: "Stunning 17th-century mosque famous for its six minarets and the blue Iznik tiles that decorate its interior.",
                        address: "Sultan Ahmet, 34122 Fatih/Istanbul",
                        url: null,
                        hours: "Open outside prayer times",
                        price: "Free",
                        phone: null,
                        lat: 41.0054, lon: 28.9768,
                        rating: 4.7, reviews: 95000,
                        thumbnail: "https://images.unsplash.com/photo-1603526206295-ef0b0bab66f1?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/blue-mosque",
                        priceAmount: 0, currency: "EUR",
                    },
                ],
            },
            {
                section: "Do", category: "Activities",
                listings: [
                    {
                        name: "Bosphorus Sunset Cruise",
                        description: "Sail along the Bosphorus strait at sunset with panoramic views of the city skyline, Ottoman palaces, and two continents.",
                        address: "Eminönü Pier, Fatih/Istanbul",
                        url: null,
                        hours: "Departures at 17:00 and 18:30",
                        price: "€28",
                        phone: null,
                        lat: 41.0172, lon: 28.9727,
                        rating: 4.6, reviews: 22000,
                        thumbnail: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/bosphorus-cruise",
                        priceAmount: 28.00, currency: "EUR",
                    },
                    {
                        name: "Cappadocia Hot Air Balloon Day Trip",
                        description: "Full-day adventure from Istanbul to Cappadocia with a sunrise hot air balloon flight over fairy chimneys.",
                        address: "Departure from Istanbul hotels",
                        url: null,
                        hours: "Departure 23:00 (arrival 05:00)",
                        price: "€189",
                        phone: null,
                        lat: 38.6431, lon: 34.8289,
                        rating: 4.7, reviews: 12000,
                        thumbnail: "https://images.unsplash.com/photo-1507041957456-9c348b3cd35b?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/cappadocia-balloon",
                        priceAmount: 189.00, currency: "EUR",
                    },
                    {
                        name: "Turkish Hammam Experience",
                        description: "Traditional Turkish bath ritual with steam, scrub and foam massage in a historic 16th-century hammam.",
                        address: "Cemberlitas, Fatih/Istanbul",
                        url: null,
                        hours: "08:00 – 22:00",
                        price: "€45",
                        phone: null,
                        lat: 41.0098, lon: 28.9718,
                        rating: 4.5, reviews: 18000,
                        thumbnail: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/hammam",
                        priceAmount: 45.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Eat", category: "Food",
                listings: [
                    {
                        name: "Istanbul Street Food Tour",
                        description: "Taste authentic Turkish street food including simit, balik ekmek, kebabs, baklava and Turkish tea with a local guide.",
                        address: "Meet at Eminönü, Fatih/Istanbul",
                        url: null,
                        hours: "Daily 10:00 – 14:00",
                        price: "€45",
                        phone: null,
                        lat: 41.0170, lon: 28.9700,
                        rating: 4.9, reviews: 8500,
                        thumbnail: "https://images.unsplash.com/photo-1530541930197-ff16ac917b0e?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/street-food-tour",
                        priceAmount: 45.00, currency: "EUR",
                    },
                    {
                        name: "Turkish Cooking Class",
                        description: "Learn to cook traditional Turkish dishes: meze, kebabs, baklava and Turkish coffee with a professional chef.",
                        address: "Beyoglu, Istanbul",
                        url: null,
                        hours: "Daily 11:00 – 15:00",
                        price: "€55",
                        phone: null,
                        lat: 41.0338, lon: 28.9779,
                        rating: 4.8, reviews: 5200,
                        thumbnail: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/cooking-class",
                        priceAmount: 55.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Drink", category: "Nightlife",
                listings: [
                    {
                        name: "Beyoglu Pub Crawl",
                        description: "Experience Istanbul nightlife with a guided pub crawl through the vibrant Beyoglu district: 4 bars, welcome drinks and local guide.",
                        address: "Start at Taksim Square, Beyoglu",
                        url: null,
                        hours: "Daily from 21:00",
                        price: "€30",
                        phone: null,
                        lat: 41.0370, lon: 28.9857,
                        rating: 4.3, reviews: 3200,
                        thumbnail: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/pub-crawl",
                        priceAmount: 30.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Buy", category: "Shopping",
                listings: [
                    {
                        name: "Grand Bazaar Shopping Experience",
                        description: "Guided tour of the historic Grand Bazaar with 4000+ shops, plus tips on bargaining and hidden artisan workshops.",
                        address: "Beyazit, 34126 Fatih/Istanbul",
                        url: null,
                        hours: "Mon-Sat 09:00 – 19:00",
                        price: "€18",
                        phone: null,
                        lat: 41.0107, lon: 28.9682,
                        rating: 4.4, reviews: 12500,
                        thumbnail: "https://images.unsplash.com/photo-1555632830-5c0a7dc4f8c6?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/grand-bazaar",
                        priceAmount: 18.00, currency: "EUR",
                    },
                    {
                        name: "Spice Bazaar Guided Walk",
                        description: "Explore the colorful Egyptian Spice Bazaar, taste Turkish delight and learn about exotic spices with a local foodie.",
                        address: "Rüstem Paşa, Eminönü",
                        url: null,
                        hours: "Daily 09:00 – 19:00",
                        price: "€22",
                        phone: null,
                        lat: 41.0165, lon: 28.9706,
                        rating: 4.5, reviews: 7800,
                        thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
                        bookingLink: "https://www.getyourguide.com/istanbul-l56/spice-bazaar",
                        priceAmount: 22.00, currency: "EUR",
                    },
                ],
            },
        ],
    },

    bangkok: {
        type: "listings",
        sections: [
            {
                section: "See", category: "Sights",
                listings: [
                    {
                        name: "Grand Palace & Wat Phra Kaew",
                        description: "Visit the stunning Grand Palace complex and the Temple of the Emerald Buddha, Thailand's most sacred religious site.",
                        address: "Na Phra Lan Rd, Phra Borom Maha Ratchawang",
                        url: "https://www.royalgrandpalace.th",
                        hours: "08:30 – 15:30",
                        price: "€14",
                        phone: null,
                        lat: 13.7500, lon: 100.4914,
                        rating: 4.7, reviews: 72000,
                        thumbnail: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/grand-palace",
                        priceAmount: 14.00, currency: "EUR",
                    },
                    {
                        name: "Wat Arun Temple of Dawn",
                        description: "Iconic riverside temple known for its intricate porcelain mosaic and central prang decorated with seashells.",
                        address: "158 Wang Doem Rd, Wat Arun, Bangkok Yai",
                        url: null,
                        hours: "08:00 – 18:00",
                        price: "€5",
                        phone: null,
                        lat: 13.7437, lon: 100.4888,
                        rating: 4.5, reviews: 45000,
                        thumbnail: "https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/wat-arun",
                        priceAmount: 5.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Do", category: "Activities",
                listings: [
                    {
                        name: "Floating Market & Long-Tail Boat Tour",
                        description: "Experience the vibrant Damnoen Saduak floating market and cruise along Bangkok's klongs on a traditional long-tail boat.",
                        address: "Pickup from Bangkok hotels",
                        url: null,
                        hours: "Departure 06:30, return 13:00",
                        price: "€38",
                        phone: null,
                        lat: 13.5189, lon: 99.9577,
                        rating: 4.5, reviews: 18000,
                        thumbnail: "https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/floating-market",
                        priceAmount: 38.00, currency: "EUR",
                    },
                    {
                        name: "Muay Thai Boxing Stadium Ticket",
                        description: "Watch an authentic Muay Thai boxing match at Rajadamnern stadium with ringside seats and cultural commentary.",
                        address: "1 Ratchadamnoen Nok Rd",
                        url: null,
                        hours: "Showtime 18:00",
                        price: "€35",
                        phone: null,
                        lat: 13.7558, lon: 100.5108,
                        rating: 4.6, reviews: 9200,
                        thumbnail: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/muay-thai",
                        priceAmount: 35.00, currency: "EUR",
                    },
                    {
                        name: "Ayutthaya Ancient Temples Day Trip",
                        description: "Day trip to the UNESCO World Heritage site of Ayutthaya with visits to ancient temples, ruins and a riverside lunch.",
                        address: "Pickup from Bangkok hotels",
                        url: null,
                        hours: "07:00 – 19:00",
                        price: "€48",
                        phone: null,
                        lat: 14.3532, lon: 100.5685,
                        rating: 4.7, reviews: 14000,
                        thumbnail: "https://images.unsplash.com/photo-1569431801373-861a30f64fc5?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/ayutthaya",
                        priceAmount: 48.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Eat", category: "Food",
                listings: [
                    {
                        name: "Thai Cooking Class with Market Visit",
                        description: "Visit a local market for fresh ingredients, then learn to cook pad thai, green curry and mango sticky rice with a chef.",
                        address: "Silom, Bangrak",
                        url: null,
                        hours: "Daily 09:00 – 14:00",
                        price: "€42",
                        phone: null,
                        lat: 13.7263, lon: 100.5141,
                        rating: 4.9, reviews: 11000,
                        thumbnail: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/cooking-class",
                        priceAmount: 42.00, currency: "EUR",
                    },
                    {
                        name: "Chinatown Night Food Tour",
                        description: "Explore Bangkok's Chinatown (Yaowarat) at night, tasting dim sum, noodles, satay and exotic fruits at street stalls.",
                        address: "Yaowarat Rd, Samphanthawong",
                        url: null,
                        hours: "Daily 18:30 – 22:30",
                        price: "€40",
                        phone: null,
                        lat: 13.7407, lon: 100.5086,
                        rating: 4.8, reviews: 8800,
                        thumbnail: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/chinatown-food",
                        priceAmount: 40.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Drink", category: "Nightlife",
                listings: [
                    {
                        name: "Rooftop Bar Hopping Night Tour",
                        description: "Visit Bangkok's best rooftop bars with panoramic city views, craft cocktails and vibrant nightlife atmosphere.",
                        address: "Meet at Siam Square",
                        url: null,
                        hours: "From 19:30",
                        price: "€55",
                        phone: null,
                        lat: 13.7218, lon: 100.5290,
                        rating: 4.4, reviews: 4100,
                        thumbnail: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/rooftop-bars",
                        priceAmount: 55.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Buy", category: "Shopping",
                listings: [
                    {
                        name: "Chatuchak Weekend Market Tour",
                        description: "Guided tour of the largest weekend market in Thailand: 15,000 stalls with clothes, crafts, antiques and street food.",
                        address: "Kamphaeng Phet 2 Rd",
                        url: null,
                        hours: "Sat-Sun 09:00 – 18:00",
                        price: "€15",
                        phone: null,
                        lat: 13.7997, lon: 100.5505,
                        rating: 4.5, reviews: 6300,
                        thumbnail: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?w=600",
                        bookingLink: "https://www.getyourguide.com/bangkok-l169/chatuchak",
                        priceAmount: 15.00, currency: "EUR",
                    },
                ],
            },
        ],
    },

    rome: {
        type: "listings",
        sections: [
            {
                section: "See", category: "Sights",
                listings: [
                    {
                        name: "Colosseum & Roman Forum Guided Tour",
                        description: "Skip-the-line guided tour of the Colosseum, Roman Forum and Palatine Hill with an expert archaeologist.",
                        address: "Piazza del Colosseo, 1",
                        url: "https://colosseo.it",
                        hours: "08:30 – 19:00",
                        price: "€52",
                        phone: "+39 06 3996 7700",
                        lat: 41.8902, lon: 12.4922,
                        rating: 4.8, reviews: 98000,
                        thumbnail: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/colosseum-tour",
                        priceAmount: 52.00, currency: "EUR",
                    },
                    {
                        name: "Vatican Museums & Sistine Chapel",
                        description: "Skip-the-line entry to the Vatican Museums, Sistine Chapel and St Peter's Basilica with an expert art historian.",
                        address: "Viale Vaticano, 00165",
                        url: "https://www.museivaticani.va",
                        hours: "09:00 – 18:00 (closed Sundays)",
                        price: "€65",
                        phone: null,
                        lat: 41.9065, lon: 12.4536,
                        rating: 4.9, reviews: 112000,
                        thumbnail: "https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/vatican-tour",
                        priceAmount: 65.00, currency: "EUR",
                    },
                    {
                        name: "Pantheon & Piazza Navona Walking Tour",
                        description: "Walking tour through Rome's historic center: the Pantheon, Piazza Navona, Trevi Fountain and Spanish Steps.",
                        address: "Meet at Piazza della Rotonda",
                        url: null,
                        hours: "Daily 10:00 and 15:00",
                        price: "€25",
                        phone: null,
                        lat: 41.8986, lon: 12.4769,
                        rating: 4.6, reviews: 34000,
                        thumbnail: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/historic-center-tour",
                        priceAmount: 25.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Do", category: "Activities",
                listings: [
                    {
                        name: "Catacombs Underground Tour",
                        description: "Explore the mysterious underground catacombs of Rome: ancient burial sites with early Christian art.",
                        address: "Via Appia Antica, 126",
                        url: null,
                        hours: "09:00 – 17:00",
                        price: "€38",
                        phone: null,
                        lat: 41.8580, lon: 12.5148,
                        rating: 4.5, reviews: 8600,
                        thumbnail: "https://images.unsplash.com/photo-1590846083693-f23fdede3a7e?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/catacombs",
                        priceAmount: 38.00, currency: "EUR",
                    },
                    {
                        name: "Villa Borghese Gardens & Gallery",
                        description: "Stroll through beautiful Villa Borghese gardens and visit the gallery with masterpieces by Bernini and Caravaggio.",
                        address: "Piazzale Scipione Borghese, 5",
                        url: null,
                        hours: "09:00 – 19:00 (closed Mondays)",
                        price: "€35",
                        phone: null,
                        lat: 41.9142, lon: 12.4922,
                        rating: 4.6, reviews: 18000,
                        thumbnail: "https://images.unsplash.com/photo-1529260830199-42c24126f198?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/villa-borghese",
                        priceAmount: 35.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Eat", category: "Food",
                listings: [
                    {
                        name: "Trastevere Street Food & Wine Tour",
                        description: "Evening food tour through charming Trastevere: supplì, pizza al taglio, gelato, and local Lazio wines.",
                        address: "Meet at Piazza Trilussa",
                        url: null,
                        hours: "Daily 18:00 – 22:00",
                        price: "€48",
                        phone: null,
                        lat: 41.8867, lon: 12.4692,
                        rating: 4.7, reviews: 12800,
                        thumbnail: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/trastevere-food",
                        priceAmount: 48.00, currency: "EUR",
                    },
                    {
                        name: "Pasta Making Class with Italian Chef",
                        description: "Hands-on cooking class where you learn to make fresh pasta from scratch with a professional Italian chef.",
                        address: "Centro Storico, Roma",
                        url: null,
                        hours: "Daily 11:00 – 14:00",
                        price: "€55",
                        phone: null,
                        lat: 41.8956, lon: 12.4820,
                        rating: 4.9, reviews: 9400,
                        thumbnail: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/pasta-class",
                        priceAmount: 55.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Drink", category: "Nightlife",
                listings: [
                    {
                        name: "Rome Evening Pub Crawl",
                        description: "Nightlife tour visiting 4 bars in Monti and Trastevere districts with welcome drinks and party atmosphere.",
                        address: "Meet at Piazza della Madonna dei Monti",
                        url: null,
                        hours: "Daily from 21:30",
                        price: "€25",
                        phone: null,
                        lat: 41.8947, lon: 12.4942,
                        rating: 4.3, reviews: 3800,
                        thumbnail: "https://images.unsplash.com/photo-1575444758702-4a6b9222c016?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/pub-crawl",
                        priceAmount: 25.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Buy", category: "Shopping",
                listings: [
                    {
                        name: "Campo de' Fiori Market Tour",
                        description: "Guided tour of Rome's most famous open-air market: fresh produce, artisanal goods and Italian delicacies.",
                        address: "Piazza Campo de' Fiori",
                        url: null,
                        hours: "Mon-Sat 07:00 – 14:00",
                        price: "€20",
                        phone: null,
                        lat: 41.8956, lon: 12.4720,
                        rating: 4.4, reviews: 5100,
                        thumbnail: "https://images.unsplash.com/photo-1506806732259-39c2d0268443?w=600",
                        bookingLink: "https://www.getyourguide.com/rome-l32/campo-dei-fiori",
                        priceAmount: 20.00, currency: "EUR",
                    },
                ],
            },
        ],
    },

    dubai: {
        type: "listings",
        sections: [
            {
                section: "See", category: "Sights",
                listings: [
                    {
                        name: "Burj Khalifa At the Top Tickets",
                        description: "Skip-the-line tickets to the observation decks of the world's tallest building with panoramic city views.",
                        address: "1 Sheikh Mohammed bin Rashid Blvd",
                        url: "https://www.burjkhalifa.ae",
                        hours: "08:30 – 23:00",
                        price: "€42",
                        phone: null,
                        lat: 25.1972, lon: 55.2744,
                        rating: 4.8, reviews: 145000,
                        thumbnail: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600",
                        bookingLink: "https://www.getyourguide.com/dubai-l173/burj-khalifa",
                        priceAmount: 42.00, currency: "EUR",
                    },
                    {
                        name: "Old Dubai Heritage Walking Tour",
                        description: "Walking tour of historic Al Fahidi district, Gold Souk, Spice Souk and traditional abra water taxi ride.",
                        address: "Meet at Al Fahidi Historical District",
                        url: null,
                        hours: "Daily 09:00 – 13:00",
                        price: "€28",
                        phone: null,
                        lat: 25.2637, lon: 55.2972,
                        rating: 4.6, reviews: 14000,
                        thumbnail: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=600",
                        bookingLink: "https://www.getyourguide.com/dubai-l173/old-dubai",
                        priceAmount: 28.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Do", category: "Activities",
                listings: [
                    {
                        name: "Desert Safari with BBQ Dinner",
                        description: "Thrilling desert safari with dune bashing, camel riding, sandboarding, and traditional BBQ dinner under the stars.",
                        address: "Pickup from Dubai hotels",
                        url: null,
                        hours: "Daily 15:00 – 21:30",
                        price: "€55",
                        phone: null,
                        lat: 25.0500, lon: 55.4000,
                        rating: 4.7, reviews: 52000,
                        thumbnail: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=600",
                        bookingLink: "https://www.getyourguide.com/dubai-l173/desert-safari",
                        priceAmount: 55.00, currency: "EUR",
                    },
                    {
                        name: "Skydiving over Palm Jumeirah",
                        description: "Tandem skydiving experience with breathtaking views over the Palm Jumeirah and Dubai coastline.",
                        address: "Skydive Dubai Dropzone",
                        url: null,
                        hours: "Book in advance",
                        price: "€620",
                        phone: null,
                        lat: 25.1124, lon: 55.1390,
                        rating: 4.9, reviews: 3400,
                        thumbnail: "https://images.unsplash.com/photo-1534766438357-2b270dbd1b40?w=600",
                        bookingLink: "https://www.getyourguide.com/dubai-l173/skydiving",
                        priceAmount: 620.00, currency: "EUR",
                    },
                    {
                        name: "Dubai Aquarium & Underwater Zoo",
                        description: "Explore one of the world's largest suspended aquariums with sharks, rays and an underwater zoo.",
                        address: "The Dubai Mall, Financial Centre Rd",
                        url: null,
                        hours: "10:00 – 22:00",
                        price: "€38",
                        phone: null,
                        lat: 25.1977, lon: 55.2797,
                        rating: 4.4, reviews: 28000,
                        thumbnail: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
                        bookingLink: "https://www.getyourguide.com/dubai-l173/aquarium",
                        priceAmount: 38.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Eat", category: "Food",
                listings: [
                    {
                        name: "Emirati Food Tour in Deira",
                        description: "Taste authentic Emirati cuisine with a local guide: machboos, luqaimat, karak chai and more traditional dishes.",
                        address: "Meet at Deira Spice Souk",
                        url: null,
                        hours: "Daily 17:00 – 21:00",
                        price: "€48",
                        phone: null,
                        lat: 25.2697, lon: 55.3095,
                        rating: 4.6, reviews: 4200,
                        thumbnail: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600",
                        bookingLink: "https://www.getyourguide.com/dubai-l173/food-tour",
                        priceAmount: 48.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Drink", category: "Nightlife",
                listings: [
                    {
                        name: "Dubai Marina Dinner Cruise",
                        description: "Luxury dinner cruise along Dubai Marina with live entertainment, buffet dinner and stunning skyline views.",
                        address: "Dubai Marina Walk",
                        url: null,
                        hours: "Daily 20:00 – 22:00",
                        price: "€65",
                        phone: null,
                        lat: 25.0762, lon: 55.1332,
                        rating: 4.5, reviews: 16000,
                        thumbnail: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=600",
                        bookingLink: "https://www.getyourguide.com/dubai-l173/dinner-cruise",
                        priceAmount: 65.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Buy", category: "Shopping",
                listings: [
                    {
                        name: "Dubai Gold & Spice Souk Tour",
                        description: "Guided tour of the famous Gold Souk and Spice Souk with tips on bargaining and traditional Middle Eastern crafts.",
                        address: "Al Ras, Deira",
                        url: null,
                        hours: "Sat-Thu 10:00 – 22:00",
                        price: "€22",
                        phone: null,
                        lat: 25.2697, lon: 55.2976,
                        rating: 4.5, reviews: 8900,
                        thumbnail: "https://images.unsplash.com/photo-1580502734024-7b31a2ca76df?w=600",
                        bookingLink: "https://www.getyourguide.com/dubai-l173/gold-souk",
                        priceAmount: 22.00, currency: "EUR",
                    },
                ],
            },
        ],
    },

    barcelona: {
        type: "listings",
        sections: [
            {
                section: "See", category: "Sights",
                listings: [
                    {
                        name: "Sagrada Familia Guided Tour",
                        description: "Skip-the-line guided tour of Gaudi's masterpiece basilica with its stunning stained glass and towering spires.",
                        address: "Carrer de Mallorca, 401",
                        url: "https://sagradafamilia.org",
                        hours: "09:00 – 20:00",
                        price: "€47",
                        phone: null,
                        lat: 41.4036, lon: 2.1744,
                        rating: 4.9, reviews: 180000,
                        thumbnail: "https://images.unsplash.com/photo-1523722929-4e658e94f0e3?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/sagrada-familia",
                        priceAmount: 47.00, currency: "EUR",
                    },
                    {
                        name: "Park Guell & Gaudi Architecture Tour",
                        description: "Explore Park Guell and Gaudi's unique architectural masterpieces including Casa Batllo and La Pedrera.",
                        address: "08024 Barcelona",
                        url: null,
                        hours: "09:30 – 19:30",
                        price: "€42",
                        phone: null,
                        lat: 41.4145, lon: 2.1527,
                        rating: 4.7, reviews: 65000,
                        thumbnail: "https://images.unsplash.com/photo-1583779457711-ab081e5b8b30?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/park-guell",
                        priceAmount: 42.00, currency: "EUR",
                    },
                    {
                        name: "Gothic Quarter Walking Tour",
                        description: "Walking tour through Barcelona's medieval Gothic Quarter with narrow streets, cathedral and hidden squares.",
                        address: "Meet at Plaça de la Catedral",
                        url: null,
                        hours: "Daily 10:00 and 16:00",
                        price: "€18",
                        phone: null,
                        lat: 41.3833, lon: 2.1761,
                        rating: 4.6, reviews: 22000,
                        thumbnail: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/gothic-quarter",
                        priceAmount: 18.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Do", category: "Activities",
                listings: [
                    {
                        name: "Kayaking along Barceloneta Beach",
                        description: "Sea kayaking experience along Barceloneta beach with views of the city skyline and Port Olimpic.",
                        address: "Barceloneta Beach",
                        url: null,
                        hours: "Daily 10:00 – 18:00",
                        price: "€30",
                        phone: null,
                        lat: 41.3809, lon: 2.1925,
                        rating: 4.5, reviews: 6700,
                        thumbnail: "https://images.unsplash.com/photo-1544551763-92ab472cad1d?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/kayaking",
                        priceAmount: 30.00, currency: "EUR",
                    },
                    {
                        name: "Montserrat Mountain Day Trip",
                        description: "Day trip to Montserrat mountain with Benedictine monastery, Black Madonna and nature trails.",
                        address: "Pickup from Barcelona center",
                        url: null,
                        hours: "08:30 – 18:00",
                        price: "€45",
                        phone: null,
                        lat: 41.5933, lon: 1.8381,
                        rating: 4.7, reviews: 24000,
                        thumbnail: "https://images.unsplash.com/photo-1551634979-2b11f8c946fe?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/montserrat",
                        priceAmount: 45.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Eat", category: "Food",
                listings: [
                    {
                        name: "La Boqueria Market Food Tour",
                        description: "Guided food tour through the famous La Boqueria market: jamon iberico, fresh seafood and Catalan tapas.",
                        address: "La Rambla, 91",
                        url: null,
                        hours: "Mon-Sat 09:00 – 15:00",
                        price: "€52",
                        phone: null,
                        lat: 41.3816, lon: 2.1719,
                        rating: 4.8, reviews: 15000,
                        thumbnail: "https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/boqueria-food",
                        priceAmount: 52.00, currency: "EUR",
                    },
                    {
                        name: "Penedes Wine Tasting Day Trip",
                        description: "Visit family-owned wineries in the Penedes region: taste cava, white and red wines with tapas pairings.",
                        address: "Pickup from Barcelona",
                        url: null,
                        hours: "09:00 – 17:00",
                        price: "€58",
                        phone: null,
                        lat: 41.3480, lon: 1.6938,
                        rating: 4.6, reviews: 7800,
                        thumbnail: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/wine-tasting",
                        priceAmount: 58.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Drink", category: "Nightlife",
                listings: [
                    {
                        name: "Barcelona Nightlife & Club Tour",
                        description: "Experience Barcelona's legendary nightlife: 3 top clubs with VIP entry, welcome drinks and a local guide.",
                        address: "Meet at Plaça Reial",
                        url: null,
                        hours: "Daily from 23:00",
                        price: "€35",
                        phone: null,
                        lat: 41.3800, lon: 2.1750,
                        rating: 4.2, reviews: 5400,
                        thumbnail: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/nightlife",
                        priceAmount: 35.00, currency: "EUR",
                    },
                ],
            },
            {
                section: "Buy", category: "Shopping",
                listings: [
                    {
                        name: "Passeig de Gràcia Shopping Tour",
                        description: "Guided shopping tour along Barcelona's most elegant avenue: luxury boutiques, Spanish designers and Gaudi architecture.",
                        address: "Passeig de Gràcia",
                        url: null,
                        hours: "Mon-Sat 10:00 – 21:00",
                        price: "€25",
                        phone: null,
                        lat: 41.3925, lon: 2.1649,
                        rating: 4.3, reviews: 2900,
                        thumbnail: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=600",
                        bookingLink: "https://www.getyourguide.com/barcelona-l45/passeig-gracia",
                        priceAmount: 25.00, currency: "EUR",
                    },
                ],
            },
        ],
    },
};

// Public API (same interface as adapters/wikivoyage.js)

/**
 * Fetch activity data for a city. Same contract as wikivoyage.js.
 * Case-insensitive city matching. Returns empty sections for unsupported cities
 * so the frontend shows "No structured activity listings found" instead of an error.
 */
export async function fetchActivitiesByCity(city) {
    const key = city.trim().toLowerCase();
    const data = CITIES[key];
    if (!data) return { type: "listings", sections: [] };
    return data;
}

/**
 * Districts are not supported by the mock provider: the mock uses a flat
 * structure. This function exists only to satisfy the adapter interface
 * and should never be called when gyg_mock is active.
 */
export async function fetchDistrictActivities(_slug) {
    throw new Error("Districts are not supported by the gyg_mock provider.");
}